[colors]
; Preto fosco com transparência suave
background = #CC1A1B26
background-alt = #33ffffff
foreground = #FFFFFF
primary = #FFFFFF
secondary = #BBBBBB
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 20pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
border-size = 0pt

padding-left = 1
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace:size=10;2
font-1 = FontAwesome:size=10;2

; Módulos ordenados: Workspaces na esquerda, Título no centro, Status e Apps (Tray) na direita
modules-left = xworkspaces
modules-center = xwindow
modules-right = pulseaudio memory cpu date tray

; Configurações do Systray (Apps em segundo plano como Discord/Wi-Fi)
tray-position = right
tray-padding = 4
tray-maxsize = 18
tray-background = ${colors.background}
tray-offset-x = 0
tray-offset-y = 0
tray-scale = 1.0

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/tray]
type = internal/tray
tray-spacing = 8px
tray-size = 65%

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
format-volume-prefix = "VOL "
label-volume = %percentage%%
format-muted = <label-muted>
label-muted = " MUDO "
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1
date = %I:%M %p
label = %date%

[settings]
screenchange-reload = true
pseudo-transparency = true